config/routes.rb
Rails.application.routes.draw do
  apipie
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :identities, path: '', controllers: { sessions: 'identities/sessions' }

  resources :character, only: [] do
    resources :traits, only: [:create, :destroy], controller: 'character_traits'
    resources :archetypes, only: [:new, :create, :destroy], controller: 'character_archetypes'
    resources :items, except: [:index, :show], controller: 'character_items'
    resources :spells, controller: 'character_spells'
    resources :descriptions, except: [:index, :show, :destroy], controller: 'character_descriptions'
  end

  namespace :admins do
    resource :dashboards, only: :show
    resources :users do
      resource :user_block, only: [:create, :destroy], as: 'block'
    end
    resources :release_notes, except: [:show]
    resources :encounters
    resources :parties do
      resource :rest, only: :update, controller: 'rest'
      resource :party_experience, only: [:edit, :update], as: 'experience'
    end

    scope module: :characters do
      resources :archetypes
      resources :adventurers
      # resources :monsters
    end

    scope module: :handbooks do
      resources :rules, except: :show
      resources :traits, except: :show
      resources :items, controller: 'base_items'
      resources :spells
      resources :races
    end

    scope module: :masteries do
      resources :abilities, except: :show
      resources :disciplines, except: :show
      resources :supports, except: :show
    end
  end

  scope module: :members do
    resource :dashboards, only: :show
    resources :adventurers
  end

  scope module: :handbooks do
    resources :rules, only: [:index, :new, :create]
    resources :traits, only: [:index, :new, :create]
    resources :spells, only: [:index, :new, :create, :show]
    resources :races, only: :index
    resources :items, only: [:index, :show], controller: 'base_items'
    resources :monsters, only: [:index, :show]
  end

  scope module: :characters do
    resources :archetypes, only: [:index, :show]
    resources :races, only: [:index, :show]
    resources :damages, only: :update
    resources :heals, only: :update
  end

  namespace :char_points, as: :char_point do
    resources :base, only: [:edit, :update], as: ''
    resources :increment, only: :update
    resources :decrement, only: :update
    resources :experiences, only: :update
  end

  namespace :api do
    devise_for :identities, path: '', only: [:sessions], controllers: { sessions: 'api/auth/sessions' }
    resources :adventurers, only: [:index, :show]
  end

  get 'news', to: 'news_feed#show', as: 'news'
  get 'search',  to: 'search#show', as: :search
  get 'autocomplete', to: 'search#autocomplete', as: :autocomplete

  authenticated :identity do
    root to: 'members/dashboards#show'
  end

  devise_scope :identity do
    root to: 'news_feed#show', as: :unsigned_root
  end
end

app/models/release_note.rb
class ReleaseNote < Note
  belongs_to :user, foreign_key: :owner_id
end

app/controllers/admins/release_notes_controller.rb
module Admins
  class ReleaseNotesController < BaseController
    def index; end
    def new; end
    def edit; end

    def create
      if new_release_note.update_attributes(release_note_params)
        flash[:success] = 'Release note was successfully published!'
        redirect_to dashboards_path
      else
        render :new
      end
    end

    def update
      if release_note.update_attributes(release_note_params)
        flash[:success] = 'Release note was successfully updated!'
        redirect_to dashboards_path
      else
        render :edit
      end
    end

    def destroy
      release_note.destroy
      flash[:success] = 'Release note was successfully removed.'
      respond_to { |format| format.js { render inline: "location.reload();" } }
    end

    private

    helper_method :release_notes
    def release_notes
      @release_notes ||= ReleaseNote.all.order(created_at: :desc)
    end

    helper_method :new_release_note
    def new_release_note
      @new_release_note ||= ReleaseNote.new(user: current_user)
    end

    helper_method :release_note
    def release_note
      @release_note ||= ReleaseNote.find(params[:id])
    end

    def release_note_params
      params.require(:release_note).permit(:title, :content, :owner_id)
    end
  end
end

app/views/admins/release_notes/_form.html.haml
= form_for [:admins, release_note], html: { class: "form form-horizontal release-note" } do |f|

  .form-group.row
    = f.label :title, class: 'col-md-2 col-form-label'
    .col-md-10
      = f.text_field :title, class: 'form-control', required: true
      = f.error_span :title

  .form-group.row
    = f.label :content, class: 'col-md-2 col-form-label'
    .col-md-10
      = f.cktext_area :content, class: 'form-control'
      = f.error_span :content

  .form-group.row
    .offset-md-2.col-md-10
      = f.submit nil,class: 'btn btn-primary'
      = link_to t('.cancel', default: t("helpers.links.cancel")), root_path, class: 'btn btn-secondary'

app/views/admins/release_notes/edit.html.haml
- model_class = ReleaseNote
.page-header
  %h1=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize

= render 'form', release_note: release_note

app/views/admins/release_notes/index.html.haml
.page-header
  %h3 Release notes

- release_notes.each do |release_note|
  .card
    .card-header
      %strong= release_note.title
    .card-block
      %blockquote
        .card-text
          %p= release_note.content.html_safe
        %footer.blockquote-footer
          %cite
            = release_note.created_at.strftime('%d %B %Y at %H:%M')
          - if current_user.admin?
            %span.pull-right
              = link_to '', edit_admins_release_note_path(release_note), class: 'fa fa--warning fa-pencil-square-o'
              = link_to '', admins_release_note_path(release_note), method: :delete, remote: true, class: 'fa fa--danger fa-trash', data: { confirm: t('.confirm',
                                                                                                                                            default: t("helpers.links.confirm",
                                                                                                                                            default: 'Are you sure?')) }

app/views/admins/release_notes/new.html.haml
- model_class = ReleaseNote
.page-header
  %h1=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize

= render 'form', release_note: new_release_note