config/routes.rb
Rails.application.routes.draw do
  apipie
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :identities, path: '', controllers: { sessions: 'identities/sessions' }

  resources :character, only: [] do
    resources :traits, only: [:create, :destroy], controller: 'character_traits'
    resources :archetypes, only: [:new, :create, :destroy], controller: 'character_archetypes'
    resources :items, except: [:index, :show], controller: 'character_items'
    resources :spells, controller: 'character_spells'
    resources :descriptions, except: [:index, :show, :destroy], controller: 'character_descriptions'
  end

  namespace :admins do
    resource :dashboards, only: :show
    resources :users do
      resource :user_block, only: [:create, :destroy], as: 'block'
    end
    resources :release_notes, except: [:show]
    resources :encounters
    resources :parties do
      resource :rest, only: :update, controller: 'rest'
      resource :party_experience, only: [:edit, :update], as: 'experience'
    end

    scope module: :characters do
      resources :archetypes
      resources :adventurers
      # resources :monsters
    end

    scope module: :handbooks do
      resources :rules, except: :show
      resources :traits, except: :show
      resources :items, controller: 'base_items'
      resources :spells
      resources :races
    end

    scope module: :masteries do
      resources :abilities, except: :show
      resources :disciplines, except: :show
      resources :supports, except: :show
    end
  end

  scope module: :members do
    resource :dashboards, only: :show
    resources :adventurers
  end

  scope module: :handbooks do
    resources :rules, only: [:index, :new, :create]
    resources :traits, only: [:index, :new, :create]
    resources :spells, only: [:index, :new, :create, :show]
    resources :races, only: :index
    resources :items, only: [:index, :show], controller: 'base_items'
    resources :monsters, only: [:index, :show]
  end

  scope module: :characters do
    resources :archetypes, only: [:index, :show]
    resources :races, only: [:index, :show]
    resources :damages, only: :update
    resources :heals, only: :update
  end

  namespace :char_points, as: :char_point do
    resources :base, only: [:edit, :update], as: ''
    resources :increment, only: :update
    resources :decrement, only: :update
    resources :experiences, only: :update
  end

  namespace :api do
    devise_for :identities, path: '', only: [:sessions], controllers: { sessions: 'api/auth/sessions' }
    resources :adventurers, only: [:index, :show]
  end

  get 'news', to: 'news_feed#show', as: 'news'
  get 'search',  to: 'search#show', as: :search
  get 'autocomplete', to: 'search#autocomplete', as: :autocomplete

  authenticated :identity do
    root to: 'members/dashboards#show'
  end

  devise_scope :identity do
    root to: 'news_feed#show', as: :unsigned_root
  end
end

app/models/trait.rb
class Trait < ApplicationRecord
  include PgSearch
  multisearchable against: :title,
                  if: [:accepted, :playable]

  validates :title,
            :description,
            :points,
            presence: true
  belongs_to :mastery
  belongs_to :user, foreign_key: :proposer_id
  delegate :name, to: :user, prefix: true, allow_nil: true
  delegate :code, to: :mastery, prefix: false
  delegate :title, to: :mastery, prefix: true
  before_save :check_playable

  scope :accepted, -> { where(accepted: true) }
  scope :proposed, -> { where(accepted: false) }
  scope :proposed_by, ->(user) { where(proposer_id: user.id) }

  private

  def check_playable
    assign_attributes(playable: false) if mastery.type == 'Support'
  end
end

app/controllers/admins/handbooks/base_controller.rb
module Admins
  module Handbooks
    class BaseController < ::Admins::BaseController
    end
  end
end

app/controllers/admins/handbooks/base_items_controller.rb
module Admins
  module Handbooks
    class BaseItemsController < BaseController
      def index; end
      def new; end
      def edit; end

      def create
        if new_item.update_attributes(item_params)
          flash[:success] = 'Item was successfully created!'
          redirect_to admins_items_path
        else
          render :new
        end
      end

      def update
        if item.update_attributes(item_params)
          flash[:success] = 'Item was successfully updated!'
          redirect_to admins_items_path
        else
          render :edit
        end
      end

      private

      helper_method :new_item
      def new_item
        @new_item ||= BaseItem.new
      end

      helper_method :item
      def item
        @item ||= BaseItem.find(params[:id])
      end

      helper_method :items
      def items
        @items ||= BaseItem.ordered
      end

      def item_params
        params.require(:base_item).permit(:title, :effect, :kind, :properties, :weight, :price, :active, :default)
      end
  end
  end
end

app/controllers/admins/handbooks/races_controller.rb
module Admins
  module Handbooks
    class RacesController < BaseController
      def index; end
      def new; end
      def edit; end
      def show; end

      def create
        if new_race.update_attributes(race_params)
          flash[:success] = 'Race was successfully created!'
          redirect_to admins_races_path
        else
          render :new
        end
      end

      def update
        if race.update_attributes(race_params)
          flash[:success] = 'Race was successfully updated!'
          redirect_to admins_races_path
        else
          render :edit
        end
      end

      def destroy
        if race.archetype.nil? && race.adventurers.blank?
          race.destroy
          flash[:success] = 'Race was successfully removed'
          redirect_to admins_races_path
        else
          flash[:warning] = 'Race cannot be removed'
          redirect_to admins_races_path
        end
      end

      private

      helper_method :new_race
      def new_race
        @new_race ||= Race.new
      end

      helper_method :race
      def race
        @race ||= Race.find(params[:id])
      end

      helper_method :races
      def races
        @races ||= Race.all.order(:id)
      end

      def race_params
        params.require(:race).permit(:code, :playable)
      end
    end
  end
end

app/controllers/admins/handbooks/rules_controller.rb
module Admins
  module Handbooks
    class RulesController < BaseController
      def index; end
      def new; end
      def edit; end

      def create
        if new_rule.update_attributes(rule_params)
          flash[:success] = 'Rule was successfully created!'
          redirect_to admins_rules_url
        else
          render :new
        end
      end

      def update
        if rule.update_attributes(rule_params)
          flash[:success] = 'Rule was successfully changed!'
          redirect_to admins_rules_url
        else
          render :edit
        end
      end

      def destroy
        rule.destroy
        flash[:warning] = 'Rule was successfully removed!'
        respond_to { |format| format.js { render inline: "location.reload();" } }
      end

      private

      helper_method :new_rule
      def new_rule
        @new_rule ||= Rule.new(group: 'Базовые правила', accepted: true)
      end

      helper_method :rule
      def rule
        @rule ||= Rule.find(params[:id])
      end

      helper_method :proposed_rules
      def proposed_rules
        @proposed_rules ||= Rule.proposed.order(:group).order(:title)
      end

      helper_method :rules
      def rules
        @rules ||= Rule.accepted.order(:group).order(:title).group_by(&:group)
      end

      helper_method :users
      def users
        @users ||= User.all
      end

      def rule_params
        params.require(:rule).permit(:title, :description, :group, :proposer_id, :accepted)
      end
  end
  end
end

app/controllers/admins/handbooks/spells_controller.rb
module Admins
  module Handbooks
    class SpellsController < BaseController
      def index; end
      def new; end
      def edit; end

      def create
        if new_spell.update_attributes(spell_params)
          flash[:success] = 'Spell was successfully created!'
          redirect_to admins_spells_path
        else
          render :new
        end
      end

      def update
        if spell.update_attributes(spell_params)
          flash[:success] = 'Spell was successfully updated!'
          redirect_to admins_spells_path
        else
          render :edit
        end
      end

      def destroy
        spell.destroy
        flash[:success] = 'Spell was successfully removed!'
        respond_to { |format| format.js { render inline: "location.reload();" } }
      end

      private

      helper_method :new_spell
      def new_spell
        @new_spell ||= Spell.new
      end

      helper_method :spell
      def spell
        @spell ||= Spell.find(params[:id])
      end

      helper_method :proposed_spells
      def proposed_spells
        @proposed_spells ||= Spell.proposed.order(:group).order(:title)
      end

      helper_method :users
      def users
        @users ||= User.all
      end

      helper_method :spells
      def spells
        @spells ||= Spell.accepted.order(:group).order(:title).group_by(&:group)
      end

      def spell_params
        params.require(:spell).permit(:title, :group, :description, :proposer_id, :accepted)
      end
    end
  end
end

app/controllers/admins/handbooks/traits_controller.rb
module Admins
  module Handbooks
    class TraitsController < BaseController
      def index; end
      def new; end
      def edit; end

      def create
        if new_trait.update_attributes(trait_params)
          flash[:success] = 'Trait was successfully created!'
          redirect_to admins_traits_url
        else
          render :new
        end
      end

      def update
        if trait.update_attributes(trait_params)
          flash[:success] = 'Trait was successfully changed!'
          redirect_to admins_traits_url
        else
          render :edit
        end
      end

      def destroy
        trait.destroy
        flash[:warning] = 'Trait was successfully removed!'
        respond_to { |format| format.js { render inline: "location.reload();" } }
      end

      private

      helper_method :new_trait
      def new_trait
        @new_trait ||= Trait.new(accepted: true)
      end

      helper_method :trait
      def trait
        @trait ||= Trait.find(params[:id])
      end

      helper_method :proposed_traits
      def proposed_traits
        @proposed_traits ||= Trait.proposed.order(:points).order(:title).joins(:mastery)
      end

      helper_method :traits
      def traits
        @traits ||= Trait.accepted.order(:points).order(:title).joins(:mastery).group_by(&:mastery)
      end

      helper_method :masteries
      def masteries
        @masteries ||= Mastery.all
      end

      helper_method :users
      def users
        @users ||= User.all
      end

      def trait_params
        params.require(:trait).permit(:title, :description, :condition, :points, :mastery_id, :proposer_id, :playable, :accepted)
      end
    end
  end
end

app/controllers/handbooks/base_controller.rb
module Handbooks
  class BaseController < ::ApplicationController
    before_action :authenticate_identity!, only: [:new, :create]
  end
end

app/controllers/handbooks/base_items_controller.rb
module Handbooks
  class BaseItemsController < BaseController
    def index
      respond_to do |format|
        format.html
        format.js { @items ||= BaseItem.ordered.active.where(kind: params[:kind]) }
      end
    end

    def show
      # respond_to :js
      # @item ||= items.find(params[:id])

      respond_to do |format|
        format.html
        format.js { @item ||= base_items.find(params[:id]) }
      end
    end

    private

    helper_method :base_items
    def base_items
      @base_items ||= BaseItem.ordered.active.order(:id)
    end

    helper_method :items
    def items
      @items ||= Item.ordered.active.order(:id)
    end

    helper_method :item
    def item
      @item ||= items.find(params[:id])
    end
  end
end

app/controllers/handbooks/monsters_controller.rb
module Handbooks
  class MonstersController < BaseController
    include Calculable

    def index; end

    def show; end

    private

    helper_method :monsters
    def monsters
      @monsters ||= $monsters.sort_by { |m| m[:info][:name] }
    end

    helper_method :monster
    def monster
      @monster ||=  $monsters.find { |x| x[:info][:name] == params[:id].downcase }
    end

    helper_method :max_hit_points
    def max_hit_points(monster)
      calc_hp(monster[:abilities][:con].to_i,
              monster[:info][:rank].to_i,
              monster[:hit_points][:bonus].to_i)
    end
  end
end

app/controllers/handbooks/races_controller.rb
module Handbooks
  class RacesController < BaseController
    def index; end

    helper_method :races
    def races
      @races ||= Race.playable
    end
  end
end

app/controllers/handbooks/rules_controller.rb
module Handbooks
  class RulesController < BaseController
    def index; end
    def new; end

    def create
      if new_rule.update_attributes(rule_params)
        flash[:success] = 'Rule was successfully proposed!'
        redirect_to rules_url
      else
        render :new
      end
    end

    private

    helper_method :rules
    def rules
      @rules ||= Rule.accepted.order(:group).order(:title).group_by(&:group)
    end

    helper_method :proposed_rules
    def proposed_rules
      @proposed_rules ||= Rule.proposed.proposed_by(current_user).order(:group).order(:title)
    end

    helper_method :new_rule
    def new_rule
      @new_rule ||= Rule.new(group: 'Базовые правила', accepted: false, user: current_user)
    end

    def rule_params
      params.require(:rule).permit(:title, :description, :group)
    end
  end
end

app/controllers/handbooks/spells_controller.rb
module Handbooks
  class SpellsController < BaseController
    def index
      respond_to do |format|
        format.html
        format.js { @spells ||= Spell.accepted.where(group: params[:group]) }
      end
    end

    def show
      respond_to :js
      @spell ||= Spell.find(params[:id])
    end

    def new; end

    def create
      if new_spell.update_attributes(spell_params)
        flash[:success] = 'Spell was successfully proposed!'
        redirect_to spells_url
      else
        render :new
      end
    end

    private

    helper_method :spells
    def spells
      @spells ||= Spell.accepted.order(:group).order(:title).group_by(&:group)
    end

    helper_method :proposed_spells
    def proposed_spells
      @proposed_spells ||= Spell.proposed.proposed_by(current_user).order(:group).order(:title)
    end

    helper_method :new_spell
    def new_spell
      @new_spell ||= Spell.new(accepted: false, user: current_user)
    end

    def spell_params
      params.require(:spell).permit(:title, :description, :group)
    end
  end
end

app/controllers/handbooks/traits_controller.rb
module Handbooks
  class TraitsController < BaseController
    def index; end
    def new; end

    def create
      if new_trait.update_attributes(trait_params)
        flash[:success] = 'Trait was successfully proposed!'
        redirect_to traits_url
      else
        render :new
      end
    end

    private

    helper_method :new_trait
    def new_trait
      @new_trait ||= Trait.new(playable: false, accepted: false, user: current_user)
    end

    helper_method :traits
    def traits
      @traits ||= Trait.accepted.where(playable: true).order(:points).order(:title).joins(:mastery).group_by(&:mastery)
    end

    helper_method :proposed_traits
    def proposed_traits
      @proposed_traits ||= Trait.proposed.proposed_by(current_user).order(:points).order(:title).joins(:mastery)
    end

    helper_method :masteries
    def masteries
      @masteries ||= Mastery.active.where(type: %w(Ability Discipline))
    end

    def trait_params
      params.require(:trait).permit(:title, :description, :condition, :points, :mastery_id)
    end
  end
end

app/views/admins/handbooks/traits/_form.html.haml
= form_for [:admins, trait], html: { class: "form form-horizontal trait" } do |f|

  .form-group.row
    = f.label :title, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :title, class: 'form-control', required: true
      = f.error_span :title

  .form-group.row
    = f.label :mastery, class: 'control-label col-lg-2'
    .col-lg-10
      .col-xs-4.col-sm-2{style: 'padding-left: 0'}
        = f.number_field :points, class: 'form-control', placeholder: 'points', required: true
        = f.error_span :points
      .col-xs-8.col-sm-10{style: 'padding-right: 0'}
        = f.select :mastery_id, options_for_select(masteries.map{ |r| [r.title, r.id] }, trait.mastery_id), { prompt: '- select -' }, { class: 'form-control', required: true }
        = f.error_span :mastery

  .form-group.row
    = f.label :condition, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :condition, class: 'form-control'
      = f.error_span :condition

  .form-group.row
    = f.label :description, class: 'control-label col-lg-2'
    .col-lg-10
      = f.cktext_area :description, class: 'form-control', required: true
      = f.error_span :description

  .form-group.row
    = f.label :proposed_by, class: 'col-md-2 col-form-label'
    .col-md-10
      = f.select :proposer_id, options_for_select(users.map{ |r| ["#{r.name} (#{r.email})", r.id] }, trait.proposer_id), { prompt: '- select -' }, { class: 'form-control', required: true }
      = f.error_span :proposer_id

  .form-group.row
    = f.label :playable, class: 'control-label col-lg-2'
    .col-lg-10
      = f.check_box :playable, class: 'form-control'
      = f.error_span :playable

  .form-group.row
    = f.label :accepted, class: 'control-label col-lg-2'
    .col-lg-10
      = f.check_box :accepted, class: 'form-control'
      = f.error_span :accepted

  .form-group.row
    .offset-lg-2.col-lg-10
      = f.submit nil,class: 'btn btn-primary'
      = link_to t('.cancel', default: t("helpers.links.cancel")), admins_traits_path, class: 'btn btn-secondary'

app/views/admins/handbooks/traits/edit.html.haml
- model_class = Trait
.page-header
  %h1=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize

= render 'form', trait: trait

app/views/admins/handbooks/traits/index.html.haml
- model_class = Trait
.page-header
  %h3
    = t '.title', default: model_class.model_name.human.pluralize.titleize
    = link_to t('.new', default: t("helpers.links.new")), new_admins_trait_path, class: 'btn btn-primary btn-sm'

.col-md-12
  - if proposed_traits.any?
    .card
      %h4.card-header.collapsed{ 'aria-controls': 'collapse_proposed',
                                 'aria-expanded': 'false',
                                 'data-parent':   '.card',
                                 'data-toggle':   'collapse',
                                 href:            '#collapse_proposed',
                                 role:            'button' }
        Proposed traits
      .card-block.collapse{ id: 'collapse_proposed' }
        - proposed_traits.each do |trait|
          %blockquote
            %h5.card-title
              = "#{trait.title} (#{trait.mastery.title} #{trait.points}+)"
              = link_to t('.edit', default: t("helpers.links.edit")), edit_admins_trait_path(trait), class: 'btn btn-secondary btn-sm'
              = link_to t('.destroy', default: t("helpers.links.destroy")),
                    admins_trait_path(trait),
                    method: :delete,
                    remote: true,
                    data: { confirm: t('.confirm',
                            default: t("helpers.links.confirm",
                            default: 'Are you sure?')) },
                    class: 'btn btn-sm btn-danger'
            .card-text
              -if trait.condition.presence
                %p
                  %b Condition:
                  = trait.condition
              %p
                = trait.description.html_safe
            .blockquote-footer
              proposed by
              %cite= trait.user_name
              on
              %cite= trait.created_at.strftime('%d %B %Y')
              %hr

  - traits.each do |mastery, trait|
    .card
      %h4.card-header.collapsed{ 'aria-controls': "collapse_#{mastery.code}",
                                 'aria-expanded': 'false',
                                 'data-parent':   '.card',
                                 'data-toggle':   'collapse',
                                 href:            "#collapse_#{mastery.code}",
                                 role:            'button' }
        = mastery.title
      .card-block.collapse{ id: "collapse_#{mastery.code}" }
        - trait.each do |trait|
          %blockquote
            %h5.card-title
              = "#{trait.title} (#{trait.mastery.title} #{trait.points}+)"
              = link_to t('.edit', default: t("helpers.links.edit")), edit_admins_trait_path(trait), class: 'btn btn-secondary btn-sm'
              = link_to t('.destroy', default: t("helpers.links.destroy")),
                admins_trait_path(trait),
                method: :delete,
                remote: true,
                data: { confirm: t('.confirm',
                        default: t("helpers.links.confirm",
                        default: 'Are you sure?')) },
                class: 'btn btn-sm btn-danger'
              - unless trait.playable
                .small.text-muted
                  not playable
            .card-text
              -if trait.condition.presence
                %p
                  %b Condition:
                  = trait.condition
              %p
                = trait.description.html_safe
            .blockquote-footer
              last updated on
              %cite= trait.updated_at.strftime('%d %B %Y')
              %hr

app/views/admins/handbooks/traits/new.html.haml
- model_class = Trait
.page-header
  %h1=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize

= render 'form', trait: new_trait