config/routes.rb
Rails.application.routes.draw do
  apipie
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :identities, path: '', controllers: { sessions: 'identities/sessions' }

  resources :character, only: [] do
    resources :traits, only: [:create, :destroy], controller: 'character_traits'
    resources :archetypes, only: [:new, :create, :destroy], controller: 'character_archetypes'
    resources :items, except: [:index, :show], controller: 'character_items'
    resources :spells, controller: 'character_spells'
    resources :descriptions, except: [:index, :show, :destroy], controller: 'character_descriptions'
  end

  namespace :admins do
    resource :dashboards, only: :show
    resources :users do
      resource :user_block, only: [:create, :destroy], as: 'block'
    end
    resources :release_notes, except: [:show]
    resources :encounters
    resources :parties do
      resource :rest, only: :update, controller: 'rest'
      resource :party_experience, only: [:edit, :update], as: 'experience'
    end

    scope module: :characters do
      resources :archetypes
      resources :adventurers
      # resources :monsters
    end

    scope module: :handbooks do
      resources :rules, except: :show
      resources :traits, except: :show
      resources :items, controller: 'base_items'
      resources :spells
      resources :races
    end

    scope module: :masteries do
      resources :abilities, except: :show
      resources :disciplines, except: :show
      resources :supports, except: :show
    end
  end

  scope module: :members do
    resource :dashboards, only: :show
    resources :adventurers
  end

  scope module: :handbooks do
    resources :rules, only: [:index, :new, :create]
    resources :traits, only: [:index, :new, :create]
    resources :spells, only: [:index, :new, :create, :show]
    resources :races, only: :index
    resources :items, only: [:index, :show], controller: 'base_items'
    resources :monsters, only: [:index, :show]
  end

  scope module: :characters do
    resources :archetypes, only: [:index, :show]
    resources :races, only: [:index, :show]
    resources :damages, only: :update
    resources :heals, only: :update
  end

  namespace :char_points, as: :char_point do
    resources :base, only: [:edit, :update], as: ''
    resources :increment, only: :update
    resources :decrement, only: :update
    resources :experiences, only: :update
  end

  namespace :api do
    devise_for :identities, path: '', only: [:sessions], controllers: { sessions: 'api/auth/sessions' }
    resources :adventurers, only: [:index, :show]
  end

  get 'news', to: 'news_feed#show', as: 'news'
  get 'search',  to: 'search#show', as: :search
  get 'autocomplete', to: 'search#autocomplete', as: :autocomplete

  authenticated :identity do
    root to: 'members/dashboards#show'
  end

  devise_scope :identity do
    root to: 'news_feed#show', as: :unsigned_root
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, uniqueness: true, presence: true

  after_save :update_identity

  has_one :identity, dependent: :destroy
  has_many :adventurers, dependent: :destroy
  has_many :rules, foreign_key: :proposer_id, dependent: :nullify
  has_many :traits, foreign_key: :proposer_id, dependent: :nullify
  has_many :spells, foreign_key: :proposer_id, dependent: :nullify
  delegate :locked_at, to: :identity, prefix: false

  accepts_nested_attributes_for :identity, update_only: true
  delegate :chat_id, to: :identity, prefix: false

  def active?
    locked_at.nil?
  end

  private

  def update_identity
    identity.update_column(:email, email) if identity && identity.email != email
  end
end

app/controllers/admins/users_controller.rb
module Admins
  class UsersController < BaseController
    def index; end
    def show; end

    def update
      user.update_attributes(user_params)
    end

    def destroy
      if user.active?
        user.identity.lock_access!
        flash[:warning] = 'User was successfully locked'
      else
        user.destroy
        flash[:warning] = 'User was successfully removed'
      end
      respond_to { |format| format.js { render inline: "location.reload();" } }
    end

    private

    helper_method :users
    def users
      @users ||= User.all.order(admin: :desc)
    end

    helper_method :user
    def user
      @user ||= User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :admin, identity_attributes: [:chat_id])
    end
  end
end

app/views/admins/users/_block_btn.html.haml
- if user.active?
  = link_to 'Block', admins_user_block_path(user), method: :post, class: 'btn btn-sm btn-outline-danger block-btn', data: { confirm: "Do you want to block #{user.name}?" }, remote: true
- else
  = link_to 'Unblock', admins_user_block_path(user), method: :delete, class: 'btn btn-sm btn-outline-success unblock-btn', data: { confirm: "Do you want to unblock #{user.name}?" }, remote: true

app/views/admins/users/_edit_card.html.haml
.card#edit
  .card-header
    Update
  .card-block
    = form_for [:admins, user], remote: true, html: { class: "form form-horizontal user" } do |f|
      .form-group
        = f.text_field :name, required: true, autofocus: true, class: 'form-control', placeholder: 'Name'
        = f.error_span :name
      .form-group
        = f.email_field :email, required: true, class: 'form-control', placeholder: 'Email'
        = f.error_span :email
      .form-group
        = f.fields_for :identity do |i|
          = i.text_field :chat_id, class: 'form-control', placeholder: 'Telegram chat_id'
          = i.error_span :chat_id
      .form-group
        Admin
        = f.check_box :admin
        %span.pull-right
          = render 'block_btn'
          = f.submit nil,class: 'btn btn-primary btn-sm'

app/views/admins/users/index.html.haml
- model_class = User
.page-header
  %h3
    = t '.title', default: model_class.model_name.human.pluralize.titleize

%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:email)
      %th= model_class.human_attribute_name(:admin)
      %th= model_class.human_attribute_name(:active)
      %th=t '.actions', default: t("helpers.actions")
  %tbody
    - users.each do |user|
      %tr{ data: { model: { id: user.id } } }
        %td= user.name
        %td= link_to user.email, admins_user_path(user)
        %td= user.admin
        %td= user.active?
        %td
          = link_to t('.destroy', :default => t("helpers.links.destroy")),
            admins_user_path(user),
            method: :delete,
            class: 'btn btn-sm btn-danger',
            remote: true,
            data: { :confirm => t('.confirm',
                    :default => t("helpers.links.confirm",
                    :default => 'Are you sure?')) }

app/views/admins/users/show.html.haml
.page-header
  %h3
    = user.name
    = link_to 'Back', admins_users_path, class: 'btn btn-secondary btn-sm'

.row
  .col-md-3
    = render 'edit_card', user: user
    .card
      .card-header
        Identity
      .card-block
        .table-responsive
          %table.table.table-striped
            %tbody
              %tr
                %th Created
                %td= user.identity.created_at
              %tr
                %th Last sign in
                %td= user.identity.current_sign_in_at
              %tr
                %th Blocked at
                %td= user.identity.locked_at

app/views/admins/users/update.js.erb
$(".card#edit").replaceWith("<%=j render('edit_card', user: user) %>");